services:

# Reverse Proxy - NGINX
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:rw
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem:ro
    depends_on:
      - mysql
    networks:
      - webnet

# SSL - LetsEncrypt
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:rw
      - /usr/share/nginx/html:/usr/share/nginx/html:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/acme.sh:/etc/acme.sh
    depends_on:
      - mysql
    networks:
      - webnet

  # Datenbank - MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD_QUINT_FELICITY: ${MYSQL_PASSWORD_QUINT_FELICITY}
    volumes:
      - ~/mysql/data:/var/lib/mysql
      # QUINT FELICITY
      - ~/websites/quint-felicity/member-quint-felicity/db-init/01-db-init.sql:/docker-entrypoint-initdb.d/quint-felicity-01.sql
      - ~/websites/quint-felicity/member-quint-felicity/db-init/02-create-user.sh:/docker-entrypoint-initdb.d/quint-felicity-02.sh
      - ~/websites/quint-felicity/member-quint-felicity/db-init/03-import-data.sql:/docker-entrypoint-initdb.d/quint-felicity-03.sql
    networks:
      - dbnet

networks:
  webnet:
    name: webnet
    driver: bridge
  dbnet:
    name: dbnet
    driver: bridge
