services:

  # Reverse Proxy - NGINX
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
#      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
    networks:
      - webnet

  # Datenbank - MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # das kann nicht sicher sein
      MYSQL_DATABASE: testdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - ~/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306" # unn√∂tog? gui geht prob eh nicht
    networks:
      - dbnet

networks:
  webnet:
    name: webnet
    driver: bridge
  dbnet:
    name: dbnet
    driver: bridge
